from masonite.routes import Route


ROUTES = [
    Route.post("/kiosk/lock", "gears.KioskController@lock").name("kiosk.lock").middleware("auth"),
    Route.post("/kiosk/unlock", "gears.KioskController@unlock").name("kiosk.unlock").middleware("auth"),
    Route.get("/gears/dashboard", "gears.DashboardController@show").name("gears.dashboard").middleware("auth"),
    Route.get("/gears/dashboard/fragment/@section", "gears.DashboardController@fragment").name("gears.dashboard.fragment").middleware("auth"),
    Route.get("/gears/dashboard/stamps", "gears.DashboardController@stamps").name("gears.dashboard.stamps").middleware("auth"),
    Route.post("/videos/dashboard", "gears.VideoController@upload").name("video.upload").middleware("auth"),
    Route.delete("/videos/dashboard/@id", "gears.VideoController@destroy").name("video.destroy").middleware("auth"),
    Route.post("/videos/dashboard/@id/idle", "gears.VideoController@set_idle").name("video.idle.set").middleware("auth"),
    Route.post("/videos/dashboard/@id/idle/clear", "gears.VideoController@clear_idle").name("video.idle.clear").middleware("auth"),
    Route.post("/archives/dashboard", "kiosk.ArchivesController@store").name("archives.store").middleware("auth"),
    Route.delete("/archives/dashboard/@id", "kiosk.ArchivesController@destroy").name("archives.destroy").middleware("auth"),
    Route.post("/events/dashboard", "gears.EventController@store").name("events.store").middleware("auth"),
    Route.post("/events/dashboard/archive", "gears.EventController@extract_from_pdf").name("events.archive").middleware("auth"),
    Route.post("/news/dashboard", "gears.NewsController@store").name("news.store").middleware("auth"),
    Route.post("/news/dashboard/layout", "gears.NewsController@layout").name("news.layout").middleware("auth"),
    Route.post("/news/dashboard/@id/body", "gears.NewsController@body").name("news.body").middleware("auth"),
    Route.post("/news/dashboard/@id/unassign", "gears.NewsController@unassign").name("news.unassign").middleware("auth"),
    Route.delete("/news/dashboard/@id", "gears.NewsController@destroy").name("news.destroy").middleware("auth"),
    Route.get("/org-board/dashboard", "gears.OrgBoardController@show").name("org-board.show").middleware("auth"),
    Route.post("/org-board/dashboard", "gears.OrgBoardController@store").name("org-board.store").middleware("auth"),
    Route.get("/org-board/dashboard/data", "gears.OrgBoardController@data").name("org-board.data").middleware("auth"),
    Route.post("/org-board/dashboard/move", "gears.OrgBoardController@move").name("org-board.move").middleware("auth"),
    Route.post("/org-board/dashboard/update", "gears.OrgBoardController@update").name("org-board.update").middleware("auth"),
    Route.post("/org-board/dashboard/photo", "gears.OrgBoardController@photo").name("org-board.photo").middleware("auth"),
    Route.post("/org-board/dashboard/delete", "gears.OrgBoardController@destroy").name("org-board.destroy").middleware("auth"),
    Route.post("/org-board/dashboard/reset-layout", "gears.OrgBoardController@reset_layout").name("org-board.reset-layout").middleware("auth"),
    Route.post("/org-board/dashboard/organization", "gears.OrgBoardController@store_organization").name("org-board.organization.store").middleware("auth"),
    Route.post("/org-board/dashboard/organization/update", "gears.OrgBoardController@update_organization").name("org-board.organization.update").middleware("auth"),
    Route.post("/org-board/dashboard/organization/delete", "gears.OrgBoardController@destroy_organization").name("org-board.organization.destroy").middleware("auth"),
    Route.post("/tour-scenes/dashboard", "kiosk.TourController@store").name("tour-scenes.store").middleware("auth"),
    Route.get ("/gears/about-lspu","kiosk.AboutController@editor").name("gears.about-lspu").middleware("auth"),
    Route.post("/gears/about-lspu/sections/@slug","kiosk.AboutController@save_section").middleware("auth"),
    Route.post("/gears/about-lspu/milestones","kiosk.AboutController@create_milestone").middleware("auth"),
    Route.post("/gears/about-lspu/milestones/@id","kiosk.AboutController@update_milestone").middleware("auth"),
    Route.post("/gears/about-lspu/milestones/@id/delete","kiosk.AboutController@delete_milestone").middleware("auth"),
    Route.post("/gears/about-lspu/milestones/@id/reorder","kiosk.AboutController@reorder_milestone").middleware("auth"),
    Route.post("/gears/about-lspu/seal/upload","kiosk.AboutController@upload_seal").middleware("auth"),
    Route.post("/gears/about-lspu/hymn/audio","kiosk.AboutController@upload_hymn_audio").middleware("auth"),
    Route.post("/gears/branding/logo", "gears.BrandingController@upload").name("branding.logo.upload").middleware("auth"),
    Route.post("/gears/branding/logo/restore", "gears.BrandingController@restore").name("branding.logo.restore").middleware("auth"),
]
