from masonite.routes import Route


ROUTES = [
    Route.post("/kiosk/lock", "KioskController@lock").name("kiosk.lock").middleware("auth"),
    Route.post("/kiosk/unlock", "KioskController@unlock").name("kiosk.unlock").middleware("auth"),
    Route.get("/gears/dashboard", "DashboardController@show").name("gears.dashboard").middleware("auth"),
    Route.get("/gears/dashboard/fragment/@section", "DashboardController@fragment").name("gears.dashboard.fragment").middleware("auth"),
    Route.get("/gears/dashboard/stamps", "DashboardController@stamps").name("gears.dashboard.stamps").middleware("auth"),
    Route.post("/videos/dashboard", "VideoController@upload").name("video.upload").middleware("auth"),
    Route.delete("/videos/dashboard/@id", "VideoController@destroy").name("video.destroy").middleware("auth"),
    Route.post("/videos/dashboard/@id/idle", "VideoController@set_idle").name("video.idle.set").middleware("auth"),
    Route.post("/videos/dashboard/@id/idle/clear", "VideoController@clear_idle").name("video.idle.clear").middleware("auth"),
    Route.post("/archives/dashboard", "ArchivesController@store").name("archives.store").middleware("auth"),
    Route.delete("/archives/dashboard/@id", "ArchivesController@destroy").name("archives.destroy").middleware("auth"),
    Route.post("/events/dashboard", "EventController@store").name("events.store").middleware("auth"),
    Route.post("/events/dashboard/archive", "EventController@extract_from_pdf").name("events.archive").middleware("auth"),
    Route.post("/news/dashboard", "NewsController@store").name("news.store").middleware("auth"),
    Route.post("/news/dashboard/layout", "NewsController@layout").name("news.layout").middleware("auth"),
    Route.post("/news/dashboard/@id/body", "NewsController@body").name("news.body").middleware("auth"),
    Route.post("/news/dashboard/@id/unassign", "NewsController@unassign").name("news.unassign").middleware("auth"),
    Route.delete("/news/dashboard/@id", "NewsController@destroy").name("news.destroy").middleware("auth"),
    Route.get("/org-board/dashboard", "OrgBoardController@show").name("org-board.show").middleware("auth"),
    Route.post("/org-board/dashboard", "OrgBoardController@store").name("org-board.store").middleware("auth"),
    Route.get("/org-board/dashboard/data", "OrgBoardController@data").name("org-board.data").middleware("auth"),
    Route.post("/org-board/dashboard/move", "OrgBoardController@move").name("org-board.move").middleware("auth"),
    Route.post("/org-board/dashboard/update", "OrgBoardController@update").name("org-board.update").middleware("auth"),
    Route.post("/org-board/dashboard/photo", "OrgBoardController@photo").name("org-board.photo").middleware("auth"),
    Route.post("/org-board/dashboard/delete", "OrgBoardController@destroy").name("org-board.destroy").middleware("auth"),
    Route.post("/org-board/dashboard/reset-layout", "OrgBoardController@reset_layout").name("org-board.reset-layout").middleware("auth"),
    Route.post("/tour-scenes/dashboard", "TourController@store").name("tour-scenes.store").middleware("auth"),
    Route.get ("/gears/about-lspu","AboutController@editor").name("gears.about-lspu").middleware("auth"),
    Route.post("/gears/about-lspu/sections/@slug","AboutController@save_section").middleware("auth"),
    Route.post("/gears/about-lspu/milestones","AboutController@create_milestone").middleware("auth"),
    Route.post("/gears/about-lspu/milestones/@id","AboutController@update_milestone").middleware("auth"),
    Route.post("/gears/about-lspu/milestones/@id/delete","AboutController@delete_milestone").middleware("auth"),
    Route.post("/gears/about-lspu/milestones/@id/reorder","AboutController@reorder_milestone").middleware("auth"),
    Route.post("/gears/about-lspu/seal/upload","AboutController@upload_seal").middleware("auth"),
    Route.post("/gears/about-lspu/hymn/audio","AboutController@upload_hymn_audio").middleware("auth"),
    Route.post("/gears/branding/logo", "BrandingController@upload").name("branding.logo.upload").middleware("auth"),
    Route.post("/gears/branding/logo/restore", "BrandingController@restore").name("branding.logo.restore").middleware("auth"),
]
