""" TourScenes Model """

from masoniteorm.models import Model


class TourScenes(Model):
    """Editor-managed mapping between Marzipano panorama scenes and the
    routable Locations table. The scene catalog itself lives in
    resources/js/data.js (generated by the tour pipeline); this table
    only stores the wiring."""

    __fillable__ = [
        "scene_id", 
        "location_id", 
        "display_name"
        ]
