"""CreateTourScenesTable Migration."""

from masoniteorm.migrations import Migration


class CreateTourScenesTable(Migration):
    def up(self):
        """
        Run the migrations.
        """
        with self.schema.create("tour_scenes") as table:
            table.increments("id")

            # Marzipano scene id from resources/js/data.js, e.g. "0-jst-1".
            # The panorama set is generated by the tour pipeline; this
            # table only stores the editor-managed wiring on top of it.
            table.string("scene_id", 32).unique()

            # Building this panorama represents. Nullable so editors can
            # park scenes that haven't been mapped yet without losing
            # their display_name override.
            table.integer("location_id").unsigned().nullable()

            # Optional override for the in-tour label. Falls back to the
            # linked location's name, then to the raw scene name.
            table.string("display_name", 120).nullable()

            table.timestamps()

            table.foreign("location_id").references("id").on("locations").on_delete("set null")

    def down(self):
        """
        Revert the migrations.
        """
        self.schema.drop("tour_scenes")
